# localization.py
# Словарь переводов для интерфейса ComprehensiveNoise

LANGUAGES = {
    'ru': 'Русский',
    'en': 'English',
}
TRANSLATIONS = {
    'title': {'ru': 'Визуализация шумов', 'en': 'Noise Visualization'},
    'mode': {'ru': 'Режим', 'en': 'Mode'},
    'mode_one': {'ru': 'Один шум', 'en': 'Single noise'},
    'mode_gallery': {'ru': 'Галерея', 'en': 'Gallery'},
    'category': {'ru': 'Категория шума', 'en': 'Noise category'},
    'type': {'ru': 'Тип шума', 'en': 'Noise type'},
    'upload': {'ru': 'Загрузить изображение (PNG/JPG)', 'en': 'Upload image (PNG/JPG)'},
    'imgsize': {'ru': 'Размер тестового изображения', 'en': 'Test image size'},
    'params': {'ru': 'Параметры шума', 'en': 'Noise parameters'},
    'desc_formula': {'ru': 'Описание и формула', 'en': 'Description and formula'},
    'original': {'ru': 'Оригинал', 'en': 'Original'},
    'with_noise': {'ru': 'С шумом', 'en': 'With noise'},
    'noise': {'ru': 'Шум', 'en': 'Noise'},
    'histograms': {'ru': 'Гистограммы: оригинал, с шумом, шум', 'en': 'Histograms: original, with noise, noise'},
    'source_code': {'ru': 'Исходный код функции шума', 'en': 'Noise function source code'},
    'caption': {'ru': '© ComprehensiveNoise, 2025', 'en': '© ComprehensiveNoise, 2025'},
    'gallery_filter': {'ru': 'Фильтрация по категориям', 'en': 'Filter by categories'},
    'gallery_header': {'ru': 'Галерея шумов', 'en': 'Noise gallery'},
    'gallery_hint': {'ru': "Выберите 'Один шум' для подробной настройки параметров.", 'en': "Select 'Single noise' for detailed parameter settings."},
    'desc': {'ru': 'Описание', 'en': 'Description'},
    'formula': {'ru': 'Формула', 'en': 'Formula'},
    'hist_orig': {'ru': 'Гистограмма оригинала', 'en': 'Original histogram'},
    'hist_noisy': {'ru': 'Гистограмма с шумом', 'en': 'Histogram with noise'},
    'hist_noise': {'ru': 'Гистограмма шума', 'en': 'Noise histogram'},
    'xlabel': {'ru': 'Значение', 'en': 'Value'},
    'ylabel': {'ru': 'Частота', 'en': 'Frequency'},
    'source_code_error': {
        'ru': 'Не удалось получить исходный код функции. Возможно, она импортирована динамически.',
        'en': 'Failed to get function source code. It may be imported dynamically.'
    }
}

NOISE_LABELS = {
    # Категории
    "1. Статистические распределения": {"ru": "Статистические распределения", "en": "Statistical Distributions"},
    "2. Цветные шумы": {"ru": "Цветные шумы", "en": "Colored Noise"},
    "3. Процедурные и синтетические шумы": {"ru": "Процедурные и синтетические шумы", "en": "Procedural and Synthetic Noise"},
    "4. Аппаратные и физические шумы": {"ru": "Аппаратные и физические шумы", "en": "Physical and Device-Based Noise"},
    "5. Окружающая среда и реальные эффекты": {"ru": "Окружающая среда и реальные эффекты", "en": "Real-World and Environmental Effects"},
    "6. Дополнительные статистические распределения": {"ru": "Дополнительные статистические распределения", "en": "Additional Statistical Distributions"},
    "7. Физические и квантовые шумы": {"ru": "Физические и квантовые шумы", "en": "Physical and Quantum Noise"},
    "8. Специализированные шумы": {"ru": "Специализированные шумы", "en": "Specialized Noise"},
    "9. Математические и теоретические шумы": {"ru": "Математические и теоретические шумы", "en": "Mathematical and Theoretical Noise"},
    "10. Шумы новых технологий": {"ru": "Шумы новых технологий", "en": "New Technology Noise"},
    "11. Комбинационные и специфические шумы": {"ru": "Комбинационные и специфические шумы", "en": "Combinational and Specific Noise"},
    "12. Шумы среды и спецэффекты": {"ru": "Шумы среды и спецэффекты", "en": "Environment and Special Effects Noise"},
    "13. Научные специализированные шумы": {"ru": "Научные специализированные шумы", "en": "Specialized Scientific Noise"},
    "14. Новейшие типы шумов": {"ru": "Новейшие типы шумов", "en": "Newest Noise Types"},
    # Примеры шумов (добавьте остальные по аналогии)
    "1.1 Gaussian Noise": {"ru": "Гауссовский шум", "en": "Gaussian Noise"},
    "1.2 Salt and Pepper Noise": {"ru": "Шум соль и перец", "en": "Salt and Pepper Noise"},
    "1.3 Poisson Noise": {"ru": "Пуассоновский шум", "en": "Poisson Noise"},
    "1.4 Speckle Noise": {"ru": "Спекл-шум", "en": "Speckle Noise"},
    "1.5 Uniform Noise": {"ru": "Равномерный шум", "en": "Uniform Noise"},
    "1.6 Rayleigh Noise": {"ru": "Шум Рэлея", "en": "Rayleigh Noise"},
    "1.7 Gamma Noise": {"ru": "Гамма-шум", "en": "Gamma Noise"},
    "1.8 Exponential Noise": {"ru": "Экспоненциальный шум", "en": "Exponential Noise"},
    "1.9 Laplacian Noise": {"ru": "Лапласовский шум", "en": "Laplacian Noise"},
    "1.10 Cauchy Noise": {"ru": "Коши-шум", "en": "Cauchy Noise"},
    "1.11 Chi-Square Noise": {"ru": "Шум хи-квадрат", "en": "Chi-Square Noise"},
    "1.12 Beta Noise": {"ru": "Бета-шум", "en": "Beta Noise"},
    "1.13 Weibull Noise": {"ru": "Вейбулловский шум", "en": "Weibull Noise"},
    "1.14 Logistic Noise": {"ru": "Логистический шум", "en": "Logistic Noise"},
    "1.15 Student's t-Noise": {"ru": "Шум Стьюдента t", "en": "Student's t-Noise"},
    "1.16 F-Distribution Noise": {"ru": "Шум F-распределения", "en": "F-Distribution Noise"},
    "1.17 Lognormal Noise": {"ru": "Логнормальный шум", "en": "Lognormal Noise"},
    "1.18 Binomial Noise": {"ru": "Биномиальный шум", "en": "Binomial Noise"},
    "1.19 Negative Binomial Noise": {"ru": "Отрицательно биномиальный шум", "en": "Negative Binomial Noise"},
    "1.20 Hypergeometric Noise": {"ru": "Гипергеометрический шум", "en": "Hypergeometric Noise"},
    "1.21 Pareto Noise": {"ru": "ПАРЕТО-шум", "en": "Pareto Noise"},
    "1.22 Maxwell-Boltzmann Noise": {"ru": "Максвелл-Больцмановский шум", "en": "Maxwell-Boltzmann Noise"},
    "2.1 White Noise": {"ru": "Белый шум", "en": "White Noise"},
    "2.2 Pink Noise": {"ru": "Розовый шум", "en": "Pink Noise"},
    "2.3 Brown Noise": {"ru": "Коричневый шум", "en": "Brown Noise"},
    "2.4 Blue Noise": {"ru": "Синий шум", "en": "Blue Noise"},
    "2.5 Violet Noise": {"ru": "Фиолетовый шум", "en": "Violet Noise"},
    "2.6 Grey Noise": {"ru": "Серый шум", "en": "Grey Noise"},
    "2.7 Red Noise": {"ru": "Красный шум", "en": "Red Noise"},
    "2.8 Orange Noise": {"ru": "Оранжевый шум", "en": "Orange Noise"},
    "2.9 Green Noise": {"ru": "Зелёный шум", "en": "Green Noise"},
    "2.10 Black Noise": {"ru": "Чёрный шум", "en": "Black Noise"},
    "3.1 Perlin Noise": {"ru": "Шум Перлина", "en": "Perlin Noise"},
    "3.2 Simplex Noise": {"ru": "Симплекс-шум", "en": "Simplex Noise"},
    "3.3 Worley Noise": {"ru": "Ворли-шум (клеточный)", "en": "Worley Noise"},
    "3.4 Fractional Brownian Motion": {"ru": "Фракционный броуновский шум", "en": "Fractional Brownian Motion"},
    "3.5 Value Noise": {"ru": "Value-шум", "en": "Value Noise"},
    "3.6 Wavelet Noise": {"ru": "Вейвлет-шум", "en": "Wavelet Noise"},
    "3.7 Diamond-Square Noise": {"ru": "Diamond-Square шум", "en": "Diamond-Square Noise"},
    "3.8 Gabor Noise": {"ru": "Габор-шум", "en": "Gabor Noise"},
    "3.9 Sparse Convolution Noise": {"ru": "Разреженный свёрточный шум", "en": "Sparse Convolution Noise"},
    "3.10 Turbulence Noise": {"ru": "Турбулентный шум", "en": "Turbulence Noise"},
    "3.11 Mosaic Noise": {"ru": "Мозаичный шум", "en": "Mosaic Noise"},
    "3.12 Ridge Noise": {"ru": "Ridge-шум", "en": "Ridge Noise"},
    "3.13 Curl Noise": {"ru": "Curl-шум", "en": "Curl Noise"},
    "3.14 Caustic Noise": {"ru": "Каустический шум", "en": "Caustic Noise"},
    "3.15 Cracks Noise": {"ru": "Шум трещин", "en": "Cracks Noise"},
    "3.16 Flow Noise": {"ru": "Шум потока", "en": "Flow Noise"},
    "4.1 Film Grain Noise": {"ru": "Зернистость пленки", "en": "Film Grain Noise"},
    "4.2 CCD/CMOS Sensor Noise": {"ru": "Шум сенсора CCD/CMOS", "en": "CCD/CMOS Sensor Noise"},
    "4.3 Thermal Noise": {"ru": "Термический шум", "en": "Thermal Noise"},
    "4.4 Fixed Pattern Noise": {"ru": "Шум фиксированного шаблона", "en": "Fixed Pattern Noise"},
    "4.5 Row/Column Noise": {"ru": "Шум строк/столбцов", "en": "Row/Column Noise"},
    "4.6 Banding Noise": {"ru": "Бандинг-шум", "en": "Banding Noise"},
    "4.7 JPEG Compression Noise": {"ru": "Шум JPEG-сжатия", "en": "JPEG Compression Noise"},
    "4.8 Quantization Noise": {"ru": "Квантование шум", "en": "Quantization Noise"},
    "4.9 Demosaicing Noise": {"ru": "Шум демозаики", "en": "Demosaicing Noise"},
    "4.10 Lens Blur": {"ru": "Размытие объектива", "en": "Lens Blur"},
    "4.11 Motion Blur": {"ru": "Шум движения (Motion Blur)", "en": "Motion Blur"},
    "4.12 Vignetting": {"ru": "Виньетирование", "en": "Vignetting"},
    "4.13 Blooming": {"ru": "Блюминг", "en": "Blooming"},
    "4.14 Chromatic Aberration": {"ru": "Хроматическая аберрация", "en": "Chromatic Aberration"},
    "4.15 Hot Pixels": {"ru": "Горячие пиксели", "en": "Hot Pixels"},
    "4.16 Dead Pixels": {"ru": "Мёртвые пиксели", "en": "Dead Pixels"},
    "4.17 Rolling Shutter Effect": {"ru": "Эффект бегущего затвора", "en": "Rolling Shutter Effect"},
    "4.18 Moiré Pattern": {"ru": "Муаровый шум", "en": "Moiré Pattern"},
    "5.1 Rain Noise": {"ru": "Шум дождя", "en": "Rain Noise"},
    "5.2 Snow Noise": {"ru": "Шум снега", "en": "Snow Noise"},
    "5.3 Fog/Haze": {"ru": "Туман/дымка", "en": "Fog/Haze"},
    "5.4 Dust and Scratches": {"ru": "Пыль и царапины", "en": "Dust and Scratches"},
    "5.5 Lens Flare": {"ru": "Блик объектива", "en": "Lens Flare"},
    "5.6 Water Droplets": {"ru": "Капли воды", "en": "Water Droplets"},
    "5.7 Smoke Effect": {"ru": "Эффект дыма", "en": "Smoke Effect"},
    "5.8 Scratched Film": {"ru": "Царапанная плёнка", "en": "Scratched Film"},
    "5.9 Glitch Effect": {"ru": "Глитч-эффект", "en": "Glitch Effect"},
    "5.10 Pixelation": {"ru": "Пикселизация", "en": "Pixelation"},
    "6.1 Rice/Rician Noise": {"ru": "Райсовский шум", "en": "Rice/Rician Noise"},
    "6.2 Von Mises Noise": {"ru": "Шум фон Мизеса", "en": "Von Mises Noise"},
    "6.3 Gumbel/Extreme Value Noise": {"ru": "Гумбелевский шум/шум экстремальных значений", "en": "Gumbel/Extreme Value Noise"},
    "6.4 Lévy Noise": {"ru": "Шум Леви", "en": "Lévy Noise"},
    "6.5 Nakagami Noise": {"ru": "Шум Накагами", "en": "Nakagami Noise"},
    "7.1 Johnson-Nyquist Noise": {"ru": "Шум Джонсона-Найквиста", "en": "Johnson-Nyquist Noise"},
    "7.2 Flicker Noise": {"ru": "Фликкер-шум", "en": "Flicker Noise"},
    "7.3 Quantum Shot Noise": {"ru": "Квантовый шум выстрела", "en": "Quantum Shot Noise"},
    "7.4 Avalanche Noise": {"ru": "Лавинный шум", "en": "Avalanche Noise"},
    "7.5 Generation-Recombination Noise": {"ru": "Шум генерации-рекомбинации", "en": "Generation-Recombination Noise"},
    "8.1 K-Distribution Noise": {"ru": "K-распределённый шум", "en": "K-Distribution Noise"},
    "8.2 Photon-Limited Noise": {"ru": "Шум с ограничением по фотонам", "en": "Photon-Limited Noise"},
    "8.3 Phase Noise": {"ru": "Фазовый шум", "en": "Phase Noise"},
    "8.4 Cosmic Noise": {"ru": "Космический шум", "en": "Cosmic Noise"},
    "8.5 Jitter Noise": {"ru": "Джиттер-шум", "en": "Jitter Noise"},
    "9.1 Lévy Stable Distribution Noise": {"ru": "Шум устойчивого распределения Леви", "en": "Lévy Stable Distribution Noise"},
    "9.2 Chaotic Noise": {"ru": "Хаотический шум", "en": "Chaotic Noise"},
    "9.3 Brownian Bridge Noise": {"ru": "Шум броуновского моста", "en": "Brownian Bridge Noise"},
    "9.4 Multifractal Noise": {"ru": "Мультифрактальный шум", "en": "Multifractal Noise"},
    "10.1 Advanced Compression Artifacts": {"ru": "Артефакты продвинутого сжатия", "en": "Advanced Compression Artifacts"},
    "10.2 HDR Artifacts Noise": {"ru": "HDR-артефакты", "en": "HDR Artifacts Noise"},
    "10.3 Deep Learning Artifacts": {"ru": "Артефакты нейросетей", "en": "Deep Learning Artifacts"},
    "11.1 Non-Stationary Noise": {"ru": "Нестационарный шум", "en": "Non-Stationary Noise"},
    "11.2 Heteroskedastic Noise": {"ru": "Гетероскедастический шум", "en": "Heteroskedastic Noise"},
    "11.3 Anisotropic Noise": {"ru": "Анизотропный шум", "en": "Anisotropic Noise"},
    "11.4 Structured Correlated Noise": {"ru": "Структурированный коррелированный шум", "en": "Structured Correlated Noise"},
    "12.1 Atmospheric Turbulence": {"ru": "Атмосферная турбулентность", "en": "Atmospheric Turbulence"},
    "12.2 Electrical Interference Patterns": {"ru": "Электрические помехи", "en": "Electrical Interference Patterns"},
    "12.3 Scanner Artifacts": {"ru": "Артефакты сканирования", "en": "Scanner Artifacts"},
    "12.4 Print Artifacts": {"ru": "Артефакты печати", "en": "Print Artifacts"},
    "12.5 Polarization Noise": {"ru": "Поляризационный шум", "en": "Polarization Noise"},
    "13.1 Spectroscopic Noise": {"ru": "Спектроскопический шум", "en": "Spectroscopic Noise"},
    "13.2 Gravitational Wave Noise": {"ru": "Шум гравитационных волн", "en": "Gravitational Wave Noise"},
    "13.3 Astronomical Noise": {"ru": "Астрономический шум", "en": "Astronomical Noise"},
    "13.4 Neuroimaging Noise": {"ru": "Шум нейровизуализации", "en": "Neuroimaging Noise"},
    "13.5 Quantum Computing Noise": {"ru": "Шум квантовых вычислений", "en": "Quantum Computing Noise"},
    "14.1 Holographic Noise": {"ru": "Голографический шум", "en": "Holographic Noise"},
    "14.2 Diffraction Noise": {"ru": "Дифракционный шум", "en": "Diffraction Noise"},
    "14.3 Mixed Reality Noise": {"ru": "Шум смешанной реальности", "en": "Mixed Reality Noise"},
    "14.4 Machine Vision Noise": {"ru": "Шум машинного зрения", "en": "Machine Vision Noise"},
    "14.5 HDR-Specific Noise": {"ru": "HDR-специфический шум", "en": "HDR-Specific Noise"},
}
